# Name: sumaira yaqoob

# Roll No: PIAIC86921

# Batch-31, Mirpur

In [1]:
#1  Import the numpy package under the name np
import numpy as np

In [2]:
#2  null vector
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
#3 ranging from 10 to 49
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
#4  shape 
x.shape

(40,)

In [43]:
#5   type 
print(x.dtype)

int32


In [8]:
#6  numpy version 
print(np.version)

<module 'numpy.version' from 'C:\\Users\\w\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [9]:
#7  numpy configuration
print(np.show_config)

<function show at 0x000001A3D0252E50>


In [44]:
#8 dimension
print(x.ndim)


1


In [45]:
#9 size
x.size

40

In [47]:
#10 all
x.all()

True

In [48]:
#11 any
x.any()

True

In [50]:
#12 identity
x=np.identity(3)


In [15]:
#13  division
arr = np.array([1, 2, 3, 4, 5]) 
arr=1/arr
arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [16]:
#14  Multiplication
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [57]:
#15  square root
x=np.array([10,12,13,14,15])
np.sqrt(x)


array([3.16227766, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

In [20]:
#16 maximum
arrax=np.random.randn(12)
ys=np.random.randn(12)
np.maximum(arrax,ys)

array([ 1.34887284,  1.44193876,  0.45205159, -0.11106339, -0.12082704,
        0.18063753,  1.13773363,  0.61998311,  0.68001486, -0.52799548,
       -0.15155498,  1.34338064])

In [21]:
#17 minimum
np.minimum(arrax,ys)

array([-0.26950062,  0.52447733,  0.02513521, -0.76560323, -0.81570171,
       -0.38214245, -0.68676472,  0.23744164,  0.27328771, -1.51052873,
       -0.54029142, -0.35929607])

In [22]:
#18  unique
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [24]:
#19 power
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [26]:
#20 ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#21 time consumed
%time

Wall time: 0 ns


In [58]:
#22 shape
x.shape

(5,)

In [31]:
#23 intersect1d
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [32]:
#24 where
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [33]:
#25 uniform
np.random.uniform(1, 15, size=(5, 3))


array([[14.00649604,  9.74509537,  9.00886946],
       [10.5473638 ,  8.57856114,  1.98235551],
       [13.66436631,  1.77846823,  6.78287316],
       [11.49370152,  3.13930029, 10.68155705],
       [ 5.11238922,  6.73014485, 10.22928519]])

In [35]:
#26 mean
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
a.mean()

3.3

In [36]:
#27 cumulate sum
a.cumsum()

array([ 1,  3,  6,  8, 11, 15, 18, 22, 27, 33], dtype=int32)

In [38]:
#28 compound
x.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [59]:
#29 sum
x.sum()

64

In [60]:
#30 sort
x.sort()

In [75]:
#31 random
data = np.random.randn(7, 4)
data

array([[-1.79844161, -1.56176932, -0.42103701, -0.58283671],
       [-0.42292305, -0.80795479,  2.04605471,  1.55796975],
       [ 0.34974701, -0.3834114 , -0.22291794, -1.67034494],
       [ 0.49815715,  0.87610603,  0.64483003, -0.76032336],
       [ 1.07427698,  1.01905828, -1.15246313, -0.93232492],
       [ 0.85140688, -0.16562221, -0.20510681,  1.80236501],
       [ 0.88123169, -1.53656811,  0.25901012, -0.53975085]])

In [84]:
#32 dot
x=np.random.randn(3,2)
y=np.random.randn(2,3)
x.dot(y)

array([[ 0.04226231, -0.69021675, -0.17245124],
       [ 0.07580373, -1.30691149, -0.32147077],
       [ 0.43982303,  0.93131049, -0.36344196]])

In [87]:
#33 transpose
x.transpose()

array([[-0.55806558, -1.06039517,  1.18980596],
       [ 0.46283265,  0.8614366 ,  1.13340685]])

In [108]:
#34 trace
x=np.array([[1,2,3,2,3,4,3,4,5,6],[1,2,3,5,5,5,5,5,5,5,]]) 
x.trace()


3

In [121]:
#35 reshape
x=np.arange(16.0)
x.reshape(2,2,4)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [132]:
#36 empty
x=np.empty(10)
x

array([4.24399158e-314, 4.24399158e-314, 8.48798317e-314, 8.48798317e-314,
       1.27319747e-313, 4.24399158e-314, 1.06099790e-313, 1.06099790e-313,
       1.06099790e-313, 1.06099790e-313])

In [134]:
#37 data
print(x.data)

In [136]:
#38 item size
print(x.itemsize)

8


In [138]:
#39 fill
x.fill(9)
x

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [142]:
#40 resize
np.resize(2,3)

array([2, 2, 2])

In [147]:
#41 dot
x.dot(2)

array([18., 18., 18., 18., 18., 18., 18., 18., 18., 18.])

In [149]:
#42 view
x.view()

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [151]:
#43 repeat
x.repeat(2)

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9.])

In [161]:
#44 flags
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [162]:
#45 save
np.save('sumaira',a)

In [164]:
#46 load
a = np.load('sumaira.npy') 
print(a)

[1 2 3 2 3 4 3 4 5 6]


In [168]:
#47 save txt
np.savetxt('sumaira',a)

In [170]:
#48 load txt
a = np.load('sumaira.npy') 
print(a )

[1 2 3 2 3 4 3 4 5 6]


In [174]:
#49 round
x=np.array([.1,.2,.3,.4])
np.round(a)

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [176]:
#50 nbytes
x.nbytes

32

In [180]:
#51 radius of circle pi
np.pi

3.141592653589793